export default {
  compilerOptions: {
    target: "es2020",
    module: "commonjs",
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    forceConsistentCasingInFileNames: true,
    outDir: "dist",
    rootDir: ".",
    sourceMap: true,
    declaration: true,
    declarationMap: true,
    noImplicitAny: true,
    strictNullChecks: true,
    strictFunctionTypes: true,
    strictBindCallApply: true,
    strictPropertyInitialization: true,
    noImplicitThis: true,
    alwaysStrict: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    noImplicitReturns: true,
    noFallthroughCasesInSwitch: true,
    noUncheckedIndexedAccess: true,
    noImplicitOverride: true,
    noPropertyAccessFromIndexSignature: true,
    allowUnusedLabels: true,
    allowUnreachableCode: true,
    exactOptionalPropertyTypes: true,
    useUnknownInCatchVariables: true,
    importsNotUsedAsValues: "error",
    isolatedModules: true,
  },
  include: ["**/*.ts"],
  exclude: ["node_modules", "dist"],
};
