name: Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t quochuydev/myapp-backend .
      - name: Publish image to Docker Hub
        run: docker push quochuydev/myapp-backend:latest
