name: CD
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  tag:
    needs: run-tests
    uses: ./.github/workflows/tag.yaml
    secrets: inherit
  build:
    needs: tag
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  # deploy:
  #   needs: build
  #   uses: ./.github/workflows/deploy.yaml
  #   secrets: inherit
