name: CD
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  create-tag:
    runs-on: ubuntu-latest
    needs: run-tests
    outputs:
      should-deploy: ${{steps.changesets.outputs.hasChangesets == 'false'}}
      version: ${{steps.get-version.outputs.version}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Create Version PR or Github Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Release Version
        if: steps.changesets.outputs.published == 'true'
        id: get-version
        run: echo "version=${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}" >> $GITHUB_OUTPUT
  deploy-to-development:
    needs: create-tag
    if: needs.create-tag.outputs.should-deploy == 'true'
    permissions:
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      version: ${{needs.create-tag.outputs.version}}
