name: CD
on:
  push:
    branches:
      - main
      - staging
      - production

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  tag:
    needs: run-tests
    uses: ./.github/workflows/tag.yaml
    secrets: inherit
  build:
    needs: run-tests
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: development
      version: ${{ github.sha }}
    secrets: inherit
