name: CI
on:
  pull_request:
    branches: [main]

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  build:
    needs: run-tests
    uses: ./.github/workflows/build.yaml
    secrets: inherit
