name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'App version'
        required: true
        type: string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull quochuydev/myapp-backend:latest
      - name: Run docker container
        run: docker run --init -d -p 3000:3000 -e ENV_PATH=.env --name myapp-backend quochuydev/myapp-backend
