name: CI

on:
  workflow_dispatch:
    inputs:
      aws-env:
        description: 'Elastic Beanstalk environment name'
        required: true
        default: 'development'
        type: string
      github-ref:
        description: 'GitHub ref'
        required: true
        default: 'main'
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Cache AWS EB CLI
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
      - name: Install AWS EB CLI
        run: pip install awsebcli
      # - name: Deploy to Elastic Beanstalk
      #   run: eb deploy --staged --env ${{ github.event.inputs.eb }}
