name: Deploy

on:
  workflow_dispatch:
    inputs:
      aws-env:
        description: 'AWS Environment'
        required: true
        default: 'development'
        type: string
      github-env:
        description: 'GitHub Environment'
        required: true
        default: 'main'
        type: string
  workflow_call:
    inputs:
      aws-env:
        description: 'AWS Environment'
        required: true
        default: 'development'
        type: string
      github-env:
        description: 'Github Environment'
        required: true
        default: 'main'
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
