name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'App version'
        required: true
        type: string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull quochuydev/myapp-backend:latest
      - name: Delete old container
        run: docker rm -f myapp-backend
      - name: Run docker container
        run: docker run -d -p 3000:3000 -e PORT=3000 --name myapp-backend quochuydev/myapp-backend
