name: Schedule

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule report
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Schedule test result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Schedule test result: ${{ job.status }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

