name: Test
on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: myapp
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Check for ESLint errors
        run: yarn lint
      - name: Install prisma packages
        run: (cd prisma && yarn install)
      - name: Apply prisma migrations
        run: (cd prisma && yarn migrate-deploy)
      - name: Run integration tests
        run: yarn test

